name: Build and Publish Extension

on: [ push ] 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x
      - name: Find latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: jbcarreon123/WebNowPlaying-Redux-Macro-Deck
          releases-only: true
        id: wnpmd
      - name: Get .csproj version
        id: version
        run: |
          [xml]$csproj = Get-Content -Path 'jbcarreon123.WebNowPlayingPlugin.csproj'
          $version = $csproj.Project.PropertyGroup.Version
          echo "::set-output name=project_version::$version"
      - name: Check if it's already published
        run: |
          if [ "${{ steps.wnpmd.outputs.tag }}" = "${{ steps.version.outputs.project_version }}" ]; then
            echo "Version already exists. Skipping build and publish."
            echo "::set-output name=is_it::true"
            exit
          fi
          echo "::set-output name=is_it::false"
        id: already-published
        shell: bash
      - name: Build Plugin
        if: ${{ steps.already-published.outputs.is_it == 'false' }}
        run: |
          dotnet publish -r=win-x64 jbcarreon123.WebNowPlayingPlugin.sln
      - name: Publish Plugin
        if: steps.already-published.outputs.is_it == 'false' && github.ref == 'refs/heads/master'
        run: |
          cd jbcarreon123.WebNowPlayingPlugin/bin/Release/net5.0/publish
          zip -r WNPl.zip .
          mv WNPl.zip $GITHUB_WORKSPACE
          mv jbcarreon123.WebNowPlayingPlugin.dll $GITHUB_WORKSPACE
        shell: bash
      - name: Create and publish Release
        if: steps.already-published.outputs.is_it == 'false' && github.ref == 'refs/heads/master'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/WNPl.zip
            ${{ github.workspace }}/jbcarreon123.WebNowPlayingPlugin.dll
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ steps.version.outputs.project_version }}
          name: WebNowPlaying Plugin ${{ steps.version.outputs.project_version }}
